#!/bin/bash

list=$(awk -F, '{ print "| " $1 " | [" $2 "](" $2 ") |" }' contributors)

awk -v list="$list" '{ if ($0 == "{{CONTRIBUTORS}}") { print list; } else { print; } }' contributors.md-template > contributors.md

awk -F, '{ print "\\author{" $1 "}" }' contributors > ag-examples-contributors.tex
