#!/bin/bash

list=$(awk -F, 'BEGIN{ styles[0] = "light"; styles[1] = "dark"; } { print "<tr class=\"" styles[NR%2] "\"> <td>" $1 "</td> <td> <a=href\"" $2 "\">" $2 "</a> </td> </tr>" }' contributors)

awk -v list="$list" '{ if ($0 == "{{CONTRIBUTORS}}") { print list; } else { print; } }' contributors.html-template > contributors.html

awk -F, '{ print "\\author{" $1 "}" }' contributors > ag-examples-contributors.tex