#!/bin/bash

list=$(awk -F, '/(^\s*$)|(^#)/ {next;} { print "| " $1 " | [" $2 "](mailto:" $2 ") |" }' contributors)

awk -v list="$list" '{ if ($0 == "{{CONTRIBUTORS}}") { print list; } else { print; } }' contributors.md-template > contributors.md

awk -F, '/(^\s*$)|(^#)/ {next;} { print "\\author{" $1 "}" }' contributors > ag-examples-contributors.tex
